name: kaboucha_jump
description: TikTok Jump Tool by Kaboucha.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter: ^6.0.3
  file_picker: ^6.1.1
  gallery_saver: ^2.3.2
  path_provider: ^2.1.1
flutter:
  uses-material-design: true
  
